### PR TITLE
Implement session storage so it can be hosted with multiple independent sessions

### PR DESCRIPTION
**Pull request by edlongman**
1. Allow it to be hosted as express sub app on top of base url. Doing this means that the app can be mounted as a sub app of another express app, allowing it to be embedded in a site like example.com/story
2. Use express-session to store progress independently for each user
3. Use relative paths to resources for mounting as installed node module
4. Provide options array to allow custom story or assets

### CODE REVIEW

**Comment by adildsw** [comment]
Hi, thank you for the contribution! These updates are great and something I've been meaning to include myself, especially the separate session for individual users.

While running your updates on my local server, I came across some issues:
1. The buttons do not trigger the next scene to load and a manual restart is required after every button press for the next page to load.
2. The _back_ button leads to a 500 status code error.
3. Some assets do not load - this was because of the forward slashes present in some of the assets in _story.json_ (my bad).

I'm not sure if these issues reflect on your end as well. Moreover, I haven't had the chance to thoroughly go through the entire list of changes, but I wanted to let you know about my findings. Regardless, it's amazing that you took interest in this project, and once again, thank you for contributing!

**Comment by edlongman** [comment]
Hi, it is a pleasure. I wanted to implement an escape room like thing and yours was the one that implemented enough features but not so many that it was stupidly complicated. Also I like the simple JSON story formatting! Next I plan on adding some Regex parsing of text results since I think just having multiple choice is too easy, but having to exactly put the right text in could be an issue.

In terms of reviewing the code I recommend ignoring whitespace in the code review (https://github.blog/2018-05-01-ignore-white-space-in-code-review/) because I wrapped everything in a function to return it and therefore indented it but that will clutter your review.

Fixed that bug! Turns out when mounting it on "/" the baseUrl comes through as "" so it was then redirecting to itself from POST to GET which then returns 404. I only tested it on a urle like "/test".
Let me know if you're still having issues

By the way I'm really not sure why your setting `window.location = window.location`. It causes some janky double loading behaviour. But when I took it out I had other loading issues

**Comment by adildsw** [comment]
Your fix works perfectly, thanks for that! 

I just came across another issue: waiting on a particular page for over approximately 10 seconds before clicking on any button resets the system back to the home page. Could potentially be the session timing out too soon.

About the JSON formatting, the idea was to create an escape-room (or basically any quiz) templating system which could be used to model custom quizzes. I had also planned on making a GUI for generating the JSON, but never got around to doing that due to the PhD stress :/

I really like your Regex idea, could potentially allow for a richer input space. Also, the regex string for each individual answer could be modelled inside the JSON item itself.

And lastly, about the `window.location = window.location` line, I was probably trying to load a responseText onto the entire HTML document, but wasn't able to get it to reload for some reason. Thus had to reload explicitly. I agree it's not the most elegant hack, but it got the job done.

**Comment by edlongman** [comment]
Ok, so fixed that, i'd set the expiry for 10800ms in the future, but it should have been 10800*1000ms!!

I've also added a name property to the session cookie so sub mounted story apps don't interfere with each other. I've hosted this on my domain just to demonstrate how you can have two separate sub apps running independantly. (http://elongman.uk/soton-escape) and (http://elongman.uk/pokemon-escape) 

Finally, I added default property settings for all of the variables read by the templates. Without this the app regularly crashes when opening two tabs and navigating them separately because the tab state is out of sync with the server record (which was changed by the other tab)

**Comment by adildsw** [comment]
This looks great! I just did a complete run through the Pokemon escape room and everything seems to be in place! Just a minor bug: I'm not able to download the playthrough logs at the end of the escape-room (500 status code). Regardless, it's crazy how much work you've put into this, thank you so much! I'm merging your pull request.

**Pull request merged**
